# Generated by Django 4.2.6 on 2023-10-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Clienti'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='cognome',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
