# Generated by Django 4.2.6 on 2023-10-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cliente_options_cliente_cognome_cliente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordinazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datadata_creazione', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ordini',
            },
        ),
        migrations.CreateModel(
            name='Piatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('Normale', 'Normale'), ('Piccante', 'Piccante'), ('Vegetariano', 'Vegetariano'), ('Vegano', 'Vegano')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Piatti',
            },
        ),
    ]
