# Generated by Django 4.2.6 on 2023-10-10 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ordinazione_piatto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinazione',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cliente'),
        ),
        migrations.AddField(
            model_name='ordinazione',
            name='piatto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.piatto'),
        ),
    ]
