# Generated by Django 4.2.6 on 2023-10-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_piatto_descrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piatto',
            name='descrizione',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
