# Generated by Django 4.2.6 on 2023-10-10 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_piatto_descrizione'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piatto',
            old_name='descrizione',
            new_name='ingredienti',
        ),
    ]
