# Generated by Django 4.2.6 on 2023-10-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_descrizione_piatto_ingredienti'),
    ]

    operations = [
        migrations.AddField(
            model_name='piatto',
            name='prezzo',
            field=models.FloatField(null=True),
        ),
    ]
