# Generated by Django 4.2.6 on 2023-10-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_piatto_prezzo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.RemoveField(
            model_name='piatto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='piatto',
            name='categoria',
            field=models.ManyToManyField(to='accounts.categoria'),
        ),
    ]
