# Generated by Django 4.2.6 on 2023-10-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_categoria_remove_piatto_categoria_piatto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piatto',
            name='ingredienti',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
