# Generated by Django 4.2.6 on 2023-10-10 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_piatto_ingredienti'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordinazione',
            options={'verbose_name_plural': 'Ordinazioni'},
        ),
    ]
