# Generated by Django 4.2.6 on 2023-10-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_ordinazione_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordinazione',
            name='piatto',
        ),
        migrations.AddField(
            model_name='ordinazione',
            name='piatto',
            field=models.ManyToManyField(null=True, to='accounts.piatto'),
        ),
    ]
