# Generated by Django 4.2.6 on 2023-10-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_datadata_creazione_ordinazione_data_creazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='piatto',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='piatti_images/'),
        ),
    ]
