# Generated by Django 4.2.6 on 2023-10-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_utente_remove_ordinazione_cliente_delete_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinazione',
            name='Utente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.utente'),
        ),
    ]
