# Generated by Django 4.2.6 on 2024-01-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_ordinazione_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utente',
            name='saldo_punti',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
