# Generated by Django 4.2.6 on 2024-01-24 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0019_utente_is_manager_utente_saldo_punti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordinazione',
            name='Utente',
        ),
        migrations.RemoveField(
            model_name='ordinazione',
            name='data_creazione',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='ordinazione',
            name='completato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordinazione',
            name='quantita',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='ordinazione',
            name='piatto',
        ),
        migrations.AddField(
            model_name='ordinazione',
            name='utente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordinazione',
            name='piatto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.piatto'),
            preserve_default=False,
        ),
    ]
