# Generated by Django 4.2.6 on 2024-01-24 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0020_remove_ordinazione_utente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinazione',
            name='utente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
