# Generated by Django 4.2.6 on 2024-01-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_ordinazione_piatto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordinazione',
            name='quantita',
        ),
    ]
