# Generated by Django 4.2.6 on 2024-01-24 21:48

from django.conf import settings
from django.db import migrations, models

from accounts.models import Utente

def associate_utente_with_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    for user in User.objects.all():
        Utente.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0027_remove_ordinazione_quantita'),
    ]

    operations = [
        migrations.RunPython(associate_utente_with_user),
        migrations.AddField(
            model_name='ordinazione',
            name='quantita',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='ordinazione',
            unique_together={('utente', 'piatto')},
        ),
    ]
