# Generated by Django 4.2.6 on 2024-01-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_ordinazione_quantita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='saldo_punti',
            field=models.IntegerField(default=0),
        ),
    ]
