# Generated by Django 4.2.6 on 2024-01-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_utente_saldo_punti'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordinazione',
            unique_together=set(),
        ),
    ]
